### ISSUE TITLE
Expressions are not checked for purity

### ISSUE THREAD

**Issue by marcoeilers** [marcoeilers/nagini#25]
Originally reported by: **Vytautas Astrauskas (Bitbucket: [vakaras](https://bitbucket.org/vakaras), GitHub: [vakaras](https://github.com/vakaras))**

----------------------------------------

The following:
```
#!python
from py2viper_contracts.contracts import *

class C:
    def __init__(self) -> None:
        self.f = 1

def bla(x: C) -> None:
    if Acc(x.f):
        pass
```
gives a stack trace:
```
#!pytb
> bin/py2viper --log debug --verifier silicon tests/translation/issues/00025.py
Traceback (most recent call last):
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 97, in verify
    vresult = verifier.verify(prog)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/verifier.py", line 67, in verify
    result = self.silicon.verify(prog)
jpype._jexception.scala.MatchErrorPyRaisable: scala.MatchError: acc(x.C_f, write) (of class viper.silver.ast.FieldAccessPredicate)
None
```

----------------------------------------
- Bitbucket: https://bitbucket.org/viperproject/py2viper-translation/issue/25

**Comment by marcoeilers** [comment]
Fixed a while ago
