### ISSUE TITLE
mypy does not catch the case when undefined function is used in lambda expression

### ISSUE THREAD

**Issue by marcoeilers** [marcoeilers/nagini#29]
Originally reported by: **Vytautas Astrauskas (Bitbucket: [vakaras](https://bitbucket.org/vakaras), GitHub: [vakaras](https://github.com/vakaras))**

----------------------------------------

The following:
```
#!python
from py2viper_contracts.contracts import *


def test() -> None:
    r = [1, 2]
    Requires(Forall(r, lambda x: (foo(x), [])))
```
gives a stack trace:

```
#!pytb
> bin/py2viper --log debug --verifier silicon tests/translation/issues/00029.py
Traceback (most recent call last):
  File "bin/py2viper", line 17, in <module>
    sys.exit(py2viper_translation.main.main())
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 176, in main
    prog = translate(python_file, jvm, args.sif)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 82, in translate
    prog = translator.translate_program(analyzer.program, sil_programs)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translator.py", line 71, in translate_program
    return self.prog_translator.translate_program(program, sil_progs, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/program.py", line 336, in translate_program
    methods.append(self.translate_method(method, ctx))
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 107, in translate_method
    return self.config.method_translator.translate_method(method, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/method.py", line 318, in translate_method
    pres, posts = self.extract_contract(method, ERROR_NAME, False, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/method.py", line 242, in extract_contract
    pres = self._translate_pres(method, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/method.py", line 60, in _translate_pres
    stmt, expr = self.translate_expr(pre, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 73, in translate_expr
    return self.config.expr_translator.translate_expr(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/expression.py", line 44, in translate_expr
    return visitor(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 99, in translate_Call
    return self.config.call_translator.translate_Call(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/call.py", line 594, in translate_Call
    return self.translate_contractfunc_call(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 144, in translate_contractfunc_call
    ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/contract.py", line 397, in translate_contractfunc_call
    return self.translate_forall(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/contract.py", line 350, in translate_forall
    body_stmt, rhs = self.translate_expr(lambda_.body.elts[0], ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 73, in translate_expr
    return self.config.expr_translator.translate_expr(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/expression.py", line 44, in translate_expr
    return visitor(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 99, in translate_Call
    return self.config.call_translator.translate_Call(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/call.py", line 598, in translate_Call
    return self.translate_normal_call(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/call.py", line 509, in translate_normal_call
    arg_stmts, args, arg_types = self._translate_args(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/call.py", line 272, in _translate_args
    target = self._get_call_target(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/call.py", line 243, in _get_call_target
    target = ctx.program.get_func_or_method(name)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/lib/program_nodes.py", line 90, in get_func_or_method
    return self.methods[name]
KeyError: 'foo'

```

----------------------------------------
- Bitbucket: https://bitbucket.org/viperproject/py2viper-translation/issue/29

**Comment by marcoeilers** [comment]
This now results in an "Encountered Any type" error, which is fine by me.
