### ISSUE TITLE
Crash when using an undefined variable in except block

### ISSUE THREAD

**Issue by marcoeilers** [marcoeilers/nagini#53]
Originally reported by: **Vytautas Astrauskas (Bitbucket: [vakaras](https://bitbucket.org/vakaras), GitHub: [vakaras](https://github.com/vakaras))**

----------------------------------------

The following:
```
#!python
from py2viper_contracts.contracts import (
    Exsures,
)


def callee() -> int:
    Exsures(Exception, True)
    raise Exception()


def caller() -> int:
    try:
        a = callee()
    except:
        return a
    return 5
```
gives a stack trace:
```
#!pytb
bin/py2viper --write-silver-to-file /tmp/py2viper.sil --verifier silicon tests/translation/issues/00053.py
Traceback (most recent call last):
  File "bin/py2viper", line 45, in <module>
    sys.exit(py2viper_translation.main.main())
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 182, in main
    prog = translate(python_file, jvm, args.sif)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 77, in translate
    analyzer.visit_module(module)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 169, in visit_module
    self.visit(self.asts[module], None)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 203, in visit
    visitor(child_node)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 187, in visit_Module
    self.visit_default(node)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 197, in visit_default
    self.visit(item, node)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 203, in visit
    visitor(child_node)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 278, in visit_FunctionDef
    self.visit(child, node)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 203, in visit
    visitor(child_node)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/analyzer.py", line 559, in visit_Try
    'handler' + handler.type.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

----------------------------------------
- Bitbucket: https://bitbucket.org/viperproject/py2viper-translation/issue/53

**Comment by marcoeilers** [comment]
Fixed a while ago.
