### ISSUE TITLE
A crash when precondition contains `Acc(x.f) == 1`

### ISSUE THREAD

**Issue by marcoeilers** [marcoeilers/nagini#60]
Originally reported by: **Vytautas Astrauskas (Bitbucket: [vakaras](https://bitbucket.org/vakaras), GitHub: [vakaras](https://github.com/vakaras))**

----------------------------------------

The following:
```
#!python
from py2viper_contracts.contracts import (
    Requires,
    Acc,
)


class C:

    def __init__(self) -> None:
        self.f = 0

    def test(self) -> None:
        Requires(
            Acc(self.f) == 1
        )
```
gives a stack trace:

```
#!pytb
>
bin/py2viper --write-silver-to-file /tmp/py2viper.sil --verifier silicon tests/translation/issues/00000.py
java.lang.IllegalArgumentException: requirement failed: expected the same typ, but got Bool and Int
        at scala.Predef$.require(Predef.scala:219)
        at viper.silver.ast.EqualityCmp.<init>(Expression.scala:818)
        at viper.silver.ast.EqCmp.<init>(Expression.scala:57)

Traceback (most recent call last):
  File "bin/py2viper", line 45, in <module>
    sys.exit(py2viper_translation.main.main())
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 219, in main
    raise e
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 182, in main
    prog = translate(python_file, jvm, args.sif)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/main.py", line 85, in translate
    prog = translator.translate_program(analyzer.program, sil_programs)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translator.py", line 85, in translate_program
    return self.prog_translator.translate_program(program, sil_progs, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/program.py", line 411, in translate_program
    methods.append(self.translate_method(method, ctx))
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 130, in translate_method
    return self.config.method_translator.translate_method(method, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/method.py", line 332, in translate_method
    pres, posts = self.extract_contract(method, ERROR_NAME, False, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/method.py", line 253, in extract_contract
    pres = self._translate_pres(method, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/method.py", line 64, in _translate_pres
    stmt, expr = self.translate_expr(pre, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/abstract.py", line 83, in translate_expr
    node, ctx, expression)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/expression.py", line 67, in translate_expr
    result =  visitor(node, ctx)
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/translators/expression.py", line 447, in translate_Compare
    self.no_info(ctx)))
  File "/data/software/projects/test/py2viper-orig/src/py2viper_translation/lib/viper_ast.py", line 301, in EqCmp
    return self.ast.EqCmp(left, right, position, info)
  File "/data/software/projects/test/py2viper-orig/deps/JPype1/jpype/_jclass.py", line 86, in _javaInit
    *args)
jpype._jexception.IllegalArgumentExceptionPyRaisable: java.lang.IllegalArgumentException: requirement failed: expected the same typ, but got Bool and Int
```

----------------------------------------
- Bitbucket: https://bitbucket.org/viperproject/py2viper-translation/issue/60

**Comment by marcoeilers** [comment]
Fixed a while ago.
